name: Generate Snake Animation ğŸ

on:
  schedule:
    - cron: "0 0 * * *"   # Corre cada dÃ­a a medianoche
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: kevintelloarevalo
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and push snake animation
        run: |
          mkdir -p dist
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Actualiza snake ğŸ" || echo "No hay cambios que hacer"
          git push origin main
